const AvilableFlatsCardData=[
    
    {
         ProjectName: 'Dhaka Housing',
         slug:"DH-1",
         location:"Exkaton", 
         description:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
         address:"1355/A, Runway Road, Dhaka- 1216",
         landarea:"26.1",
         projecttype:"commercial",
         nbuildblock:"2",
         nfloor:"5",
         flatsize:"800(sqf)",
         launch:"15, January 2023",
        completedate:"Friday, March 2022",
         rapprovaldate:"Sunday, June 2020",
         rapprovalno:"RAJUK202526",
         status:"Handover",
         img:"/b1.jpg"
    },
    {
        ProjectName: 'Apon Nibash',
        slug:"AN-1",
        location:"Exkaton",
        description:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
        address:"1355/A, Runway Road, Dhaka- 1216",
        landarea:"26.1",
        projecttype:"commercial",
        nbuildblock:"2",
        nfloor:"5",
        flatsize:"800(sqf)",
        launch:"15, January 2023",
        completedate:"Friday, March 2022",
         rapprovaldate:"Sunday, June 2020",
         rapprovalno:"RAJUK202526",
         status:"Handover",
         img:"/b2.jpg"
   },
   {
    ProjectName: 'Amader Bari',
    slug:"AB-1",
    location:"Exkaton",
    description:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    address:"1355/A, Runway Road, Dhaka- 1216",
    landarea:"26.1",
    projecttype:"commercial",
    nbuildblock:"2",
    nfloor:"5",
    flatsize:"800(sqf)",
    launch:"15, January 2023",
        completedate:"Friday, March 2022",
         rapprovaldate:"Sunday, June 2020",
         rapprovalno:"RAJUK202526",
         status:"Handover",
         img:"/b3.jpg"
},
{
    ProjectName: 'Bristi Bilash',
    slug:"BB-1",
    location:"Exkaton",
    description:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    address:"1355/A, Runway Road, Dhaka- 1216",
    landarea:"26.1",
    projecttype:"commercial",
    nbuildblock:"2",
    nfloor:"5",
    flatsize:"800(sqf)",
    launch:"15, January 2023",
        completedate:"Friday, March 2022",
         rapprovaldate:"Sunday, June 2020",
         rapprovalno:"RAJUK202526",
         status:"Handover",
         img:"/b4.jpg"
},
{
    ProjectName: 'Apon Ghor',
    slug:"AG-1",
    location:"Exkaton",
    description:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    address:"1355/A, Runway Road, Dhaka- 1216",
    landarea:"26.1",
    projecttype:"commercial",
    nbuildblock:"2",
    nfloor:"5",
    flatsize:"800(sqf)",
    launch:"15, January 2023",
        completedate:"Friday, March 2022",
         rapprovaldate:"Sunday, June 2020",
         rapprovalno:"RAJUK202526",
         status:"Handover",
         img:"/b5.jpg"
},
{
    ProjectName: 'Shopner Nibash',
    slug:"SN-1",
    location:"Exkaton",
    description:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    address:"1355/A, Runway Road, Dhaka- 1216",
    landarea:"26.1",
    projecttype:"commercial",
    nbuildblock:"2",
    nfloor:"5",
    flatsize:"800(sqf)",
    launch:"15, January 2023",
        completedate:"Friday, March 2022",
         rapprovaldate:"Sunday, June 2020",
         rapprovalno:"RAJUK202526",
         status:"Handover",
         img:"/b6.jpg"
},
{
    ProjectName: 'Dhaka Housing',
    slug:"Dh-1",
    location:"Exkaton",
    description:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    address:"1355/A, Runway Road, Dhaka- 1216",
    landarea:"26.1",
    projecttype:"commercial",
    nbuildblock:"2",
    nfloor:"5",
    flatsize:"800(sqf)",
    launch:"15, January 2023",
        completedate:"Friday, March 2022",
         rapprovaldate:"Sunday, June 2020",
         rapprovalno:"RAJUK202526",
         status:"Handover",
         img:"/b7.jpg"
},
{
    ProjectName: 'Amader Bari',
    slug:"AB-1",
    location:"Exkaton",
    description:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    address:"1355/A, Runway Road, Dhaka- 1216",
    landarea:"26.1",
    projecttype:"commercial",
    nbuildblock:"2",
    nfloor:"5",
    flatsize:"800(sqf)",
    launch:"15, January 2023",
        completedate:"Friday, March 2022",
         rapprovaldate:"Sunday, June 2020",
         rapprovalno:"RAJUK202526",
         status:"Handover",
         img:"/b8.jpg"
},
{
    ProjectName: 'Notun Bari',
    slug:"NB-1",
    location:"Exkaton",
    description:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    address:"1355/A, Runway Road, Dhaka- 1216",
    landarea:"26.1",
    projecttype:"commercial",
    nbuildblock:"2",
    nfloor:"5",
    flatsize:"800(sqf)",
    launch:"15, January 2023",
        completedate:"Friday, March 2022",
         rapprovaldate:"Sunday, June 2020",
         rapprovalno:"RAJUK202526",
         status:"Handover",
         img:"/b9.jpg"
},
{
    ProjectName: 'Amar Prashad',
    slug:"AP-1",
    location:"Exkaton",
    description:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    address:"1355/A, Runway Road, Dhaka- 1216",
    landarea:"26.1",
    projecttype:"commercial",
    nbuildblock:"2",
    nfloor:"5",
    flatsize:"800(sqf)",
    launch:"15, January 2023",
        completedate:"Friday, March 2022",
         rapprovaldate:"Sunday, June 2020",
         rapprovalno:"RAJUK202526",
         status:"Handover",
         img:"/b10.jpg"
},



]

export default AvilableFlatsCardData